### ISSUE TITLE
Home page title.

### ISSUE THREAD

**Issue by hrzepa** [ICHPC/hpc-repo#28]
The initial home page announces

Repository for computational datasets generated on the Imperial College High Performance Computing Service resources.

General practise with this repository has resulted in a lot of instrumental data being deposited, data which was  NOT created using the  HPC resources.

Can a more general title that reflects this be considered?

**Comment by mj-harvey** [comment]
That text is now changed to remove reference to  HPC.  Better page content will follow as part of overarching RCS web improvements
