### ISSUE TITLE
Metadata not deletable

### ISSUE THREAD

**Issue by hrzepa** [ICHPC/hpc-repo#46]
Eg Entry https://data.hpc.imperial.ac.uk/resolve/?doi=1619&access=rvp2-pq7v

in edit mode, trying to delete eg Usage: babel [-i<input-type>] <name> [-o<output-type>] <name>.

Select the entry, then press delete selection.  Nothing happens!

**Comment by mj-harvey** [comment]
Fixed for editing entry

**Comment by mj-harvey** [comment]
fixed  everywhere now
